- hosts: centos.my
  vars: 
    zabbix_server_ip: 51.250.100.40
    zabbix_agent_ip: centos

  tasks:
          #    - name: install zabbix_client
          #      shell: rpm -Uvh https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm  
    - name: Install zabbix agent
      shell: yum -y install zabbix-agent
    - name: modify zabbix server ip address
      shell: sed -i 's#Server=127.0.0.1#Server='{{zabbix_server_ip}}'#g' /etc/zabbix/zabbix_agentd.conf
    - name: modify zabbix server active ip addr
      shell: sed -i 's/ServerActive=127.0.0.1/ServerActive='{{zabbix_server_ip}}'/g' /etc/zabbix/zabbix_agentd.conf
    - name: Enable remote command execution
      shell: sed -i 's/# EnableRemoteCommands=0/EnableRemoteCommands=1'/g /etc/zabbix/zabbix_agentd.conf
    - name: Enable remote command logs
      shell: sed -i 's/# LogRemoteCommands=0/LogRemoteCommands=1'/g /etc/zabbix/zabbix_agentd.conf
    - name: modify zabbix agent hostname
      shell: sed -i 's/Hostname=Zabbix server/Hostname='{{zabbix_agent_ip}}'/g' /etc/zabbix/zabbix_agentd.conf
    - name: enable zabbix-agent
      shell: systemctl start zabbix-agent ;systemctl enable zabbix-agent
- hosts: ubuntu.my
  vars:
    zabbix_server_ip: 127.0.0.1
    zabbix_agent_ip: zabbix

  tasks:
          #    - name: install zabbix_client
      #      shell: wget https://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-1+focal_all.deb
      #      shell: dpkg -i zabbix-release_5.0-1+focal_all.deb
      #      shell: apt update
    - name: Install zabbix agent
      shell: apt -y install zabbix-agent
    - name: modify zabbix server ip address
      shell: sed -i 's#Server=127.0.0.1#Server='{{zabbix_server_ip}}'#g' /etc/zabbix/zabbix_agentd.conf
    - name: modify zabbix server active ip addr
      shell: sed -i 's/ServerActive=127.0.0.1/ServerActive='{{zabbix_server_ip}}'/g' /etc/zabbix/zabbix_agentd.conf
    - name: Enable remote command execution
      shell: sed -i 's/# EnableRemoteCommands=0/EnableRemoteCommands=1'/g /etc/zabbix/zabbix_agentd.conf
    - name: Enable remote command logs
      shell: sed -i 's/# LogRemoteCommands=0/LogRemoteCommands=1'/g /etc/zabbix/zabbix_agentd.conf
    - name: modify zabbix agent hostname
      shell: sed -i 's/Hostname=Zabbix server/Hostname='{{zabbix_agent_ip}}'/g' /etc/zabbix/zabbix_agentd.conf
    - name: enable zabbix-agent
      shell: systemctl start zabbix-agent ;systemctl enable zabbix-agent
      

